services:
  web:
    build:
      context: flask-server
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:PASSWORD_PLACEHOLDER@db/company
      - DATABASE_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password
    ports:
      - '8000:8000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    depends_on:
      db:
        condition: service_healthy

  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./mariadb/:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=company
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt 
